site_name: Sduino
site_description: Programming the STM8S the Arduino way
site_author: Michael Mayer
repo_url: 'https://github.com/tenbaht/sduino'
# using mkdocs 1.0.4 now
nav:
    - User Guide:
        - Introduction: 'index.md'
        - Automatic Installation: 'usage/board-manager-install.md'
        - Building with the IDE: 'usage/build-ide.md'
        - When to use an STM8S - and when not: 'usage/why-stm8.md'
        - Manual Installation: 'usage/manual-install.md'
        - Building with a Makefile: 'usage/build-cli.md'
        - Limitations: 'usage/limitations.md'
        - Status and todo: 'usage/status-todo.md'
    - Libraries:
        - API description and migration guidelines: api/migration.md
        - Print: api/Print.md
        - HardwareSerial: api/HardwareSerial.md
        - SPI: api/SPI.md
        - Wire: api/Wire.md
        - I2C: api/I2C.md
        - LiquidCrystal character LCD library: api/LiquidCrystal.md
        - LiquidCrystal_I2C character LCD connected via I2C backpack boards: api/LiquidCrystal_I2C.md
        - LiquidCrystal_pcf2119 character LCD connected via I2C: api/LiquidCrystal_pcf2119.md
        - PCD8544 libray for Nokia 5110-like graphical LCDs: api/PCD8544.md
        - Mini_SSD1306 library for monochrome OLED-displays: api/Mini_SSD1306.md
        - Stepper library: api/Stepper.md
        - Servo library: api/Servo.md
    - Hardware:
        - Flash tool: hardware/flashtool.md
#        - List of supported boards: hardware.md
        - 'Generic STM8S103F3 breakout board (stm8blue)': hardware/stm8blue.md
        - 'ESP14 Wifi board (STM8S003F3P6)': hardware/esp14.md
        - 'W1209 thermostat board (STM8S003F3P6)': 'hardware/w1209-thermostat.md'
        - 'Generic STM8S105K4 breakout board (stm8sblack)': hardware/stm8sblack.md
        - 'STM8S105Discovery evaluation board made by ST (STM8S105C6)': hardware/stm8sdiscovery.md
        - 'sduino Uno (STM8S105K6), inspired by Arduino Uno': https://github.com/roybaer/sduino_uno
        - 'sduino MB (STM8S208MB), inspired by Arduino Mega': https://github.com/roybaer/sduino_mb
    - Developer Guide:
        - IDE integration: 'developer/ide-integration.md'
        - Compiling the tools: 'developer/compiling-the-tools.md'
        - Update an automatic installation to a manual installation: 'developer/update-to-manual.md'
        - C preprocessor macro magic: 'developer/macro.md'
        - Ways to define a pin mapping: 'developer/pin_mapping.md'
        - Using the SDCC compiler: 'developer/sdcc.md'
        - Using the SPL with SDCC and sduino: 'developer/spl.md'
        - Bare metal programming on the STM8: 'developer/bare-metal-programming.md'
        - Performance comparison and benchmarking: 'developer/performance.md'
        - Links and further reading: 'developer/links.md'
    - Contact: contact.md
    - About: about.md

#- theme: amelia
#+++ theme: bootstrap		leicht, elegant
#+ theme: cerulean
#+++ theme: cosmo		elegant, ausgewogen
#- theme: cyborg		zu starker Kontrast
#++ theme: flatly		grau-blau
#++ theme: journal		Überschriften evtl. etwas zu schwer
#+++ theme: mkdocs		leicht, elegant. Wie Bootstrap. Mit Search
#+ theme: readable
#o theme: readthedocs		komplette Übersicht, Suche
#++ theme: simplex		elegant, Schrift evtl. etwas zu klein
#- theme: slate			zu starker Kontrast
#++ theme: spacelab		elegant und leicht, grau
#+++ theme: united		Orange. Ausgewogen.
#+++ theme: yeti		sehr gut. Leicht, elegant
# best: flatly, yeti (light typeface), cosmo, united, spacelab
# with search: mkdocs
#theme: flatly
theme: bootstrap
#theme: mkdocs
